
# Inspiration taken from https://github.com/felipewom/docker-compose-postgres/

services:
    db:
        image: 'postgres:latest'

        environment:
            POSTGRES_PASSWORD: changeme # PostgreSQL password to connect to DB (CHANGE ME!!!)
        
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

        networks:
            - backend
        
        volumes:
            - ${PWD}/sql/dbdata/:/var/lib/postgresql/data/
            - ${PWD}/sql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

    
    # This is a web app GUI to view the database. Added for development convenience/debug
    # but does not need to be run in final product
    pgadmin:
        image: dpage/pgadmin4
        
        ports:
            - 5433:80
        environment:
            PGADMIN_DEFAULT_EMAIL: test@localhost.lan
            PGADMIN_DEFAULT_PASSWORD: password
        depends_on:
            - db

        networks:
            - backend
        volumes:
            - ${PWD}/sql/pgadmin-data/:/var/lib/pgadmin/
    
    web:
        build: .
        ports:
            - 8080:8080
        depends_on:
            db:
                condition: service_healthy
                restart: true
        networks:
            - backend
networks:
    backend:
        driver: bridge
